name: budgetizer_dart
description: A pure Dart library for budgetizer core logic.
version: 0.1.0
environment:
  sdk: '>=3.2.0 <4.0.0'

publish_to: 'none'

dependencies:
  http: ^1.2.0
  path: ^1.9.0
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  sqflite_common: ^2.5.0
  sqflite_common_ffi: ^2.3.0 # Added for CLI support
  meta: ^1.11.0
  uuid: ^4.3.3 # Likely needed for ID generation
  plaid_dart:
    path: ../plaid_dart
  excel: ^4.0.6
  google_generative_ai: ^0.4.7

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.8
  riverpod_generator: ^3.0.3
