name: budgetizer_workspace
description: A monorepo for the Budgetizer budgeting suite.
environment:
  sdk: ^3.5.0

workspace:
  - apps/cli
  - apps/desktop
  - packages/budgetizer_dart
  - packages/plaid_dart
